# Generated by Django 5.1.3 on 2025-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
